apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local:80

    useEqualHeights: true

    layout:
      Media:
        style: row
        columns: 4
      Services:
        style: row
        columns: 4
      Cluster Management:
        style: row
        columns: 4
      TrueNAS:
        style: row
        columns: 4
      Networking:
        style: row
        columns: 4

  bookmarks.yaml: |
    - Development:
      - Github:
        - icon: github
          href: https://github.com/
    - Hetzner:
      - konsoleH:
        - icon: hetzner
          href: https://konsoleh.hetzner.com/
      - DNS Console:
        - icon: hetzner
          href: http://dns.hetzner.com/
      - KH Webmail:
        - icon: hetzner
          href: https://webmail.your-server.de/
      - Cloud Console:
        - icon: hetzner
          href: https://console.hetzner.com/

  services.yaml: |
    - Media:
      - Jellyfin:
          icon: jellyfin.png
          href: https://jellyfin.kennyandries.com/
          description: Media streaming
          namespace: servarr
          app: jellyfin
          siteMonitor: http://servarr-jellyfin.servarr.svc.cluster.local:8096
      - Radarr:
          icon: radarr.png
          href: https://radarr.kennyandries.com/
          description: Movie requesting
          namespace: servarr
          app: radarr
          siteMonitor: http://servarr-radarr.servarr.svc.cluster.local:7878
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.kennyandries.com/
          description: Series requesting
          namespace: servarr
          app: sonarr
          siteMonitor: http://servarr-sonarr.servarr.svc.cluster.local:80
      - Lidarr:
          icon: lidarr.png
          href: https://lidarr.kennyandries.com/
          description: Music requesting
          namespace: servarr
          app: lidarr
          siteMonitor: http://servarr-lidarr.servarr.svc.cluster.local:8686
      - Prowlarr:
          icon: prowlarr.png
          href: https://prowlarr.kennyandries.com/
          description: Indexer management
          namespace: servarr
          app: prowlarr
          siteMonitor: http://servarr-prowlarr.servarr.svc.cluster.local:9696
      - Jellyseerr:
          icon: jellyseerr.png
          href: https://jellyseerr.kennyandries.com/
          description: Media requesting
          namespace: servarr
          app: jellyseerr
          siteMonitor: http://servarr-jellyseerr.servarr.svc.cluster.local:5055
      - Bazarr:
          icon: bazarr.png
          href: https://bazarr.kennyandries.com/
          description: Subtitle management
          namespace: servarr
          app: bazarr
          siteMonitor: http://servarr-bazarr.servarr.svc.cluster.local:6767
      - Cleanuparr:
          icon: cleanuperr.png
          href: https://cleanuparr.kennyandries.com/
          description: Media cleanup
          namespace: servarr
          app: cleanuparr
          siteMonitor: http://servarr-cleanuparr.servarr.svc.cluster.local:11011
      - qBittorrent:
          icon: qbittorrent.png
          href: https://qbittorrent.kennyandries.com/
          description: Torrent client
          namespace: servarr
          app: qbittorrent
          siteMonitor: http://servarr-qbittorrent-web.servarr.svc.cluster.local:8080

    - Services:
      - Actual Budget:
          icon: actual-budget.png
          href: https://actualbudget.kennyandries.com/
          description: Personal finance
          namespace: actualbudget
          app: actualbudget
          siteMonitor: http://actualbudget.actualbudget.svc.cluster.local:5006

    - Cluster Management:
      - Traefik:
          icon: traefik.png
          href: https://traefik.kennyandries.com/
          description: Ingress controller
          namespace: traefik
          app: traefik
          siteMonitor: https://traefik.kennyandries.com
      - Longhorn:
          icon: longhorn.png
          href: https://longhorn.kennyandries.com/
          description: Distributed block storage
          namespace: longhorn-system
          app: longhorn
          siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local:80

    - TrueNAS:
      - pkb-nas-tns-1:
          icon: truenas.png
          href: https://pkb-nas-tns-1/
          description: Network attached storage
          siteMonitor: https://pkb-nas-tns-1
      - plb-nas-tns-1:
          icon: truenas.png
          href: https://192.168.2.2/
          description: Network attached storage
          siteMonitor: https://192.168.2.2

    - Networking:
      - UniFi Express 7:
          icon: unifi.png
          href: https://192.168.1.1/
          description: Router
          siteMonitor: https://192.168.1.1

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
    - longhorn:
        # Show the expanded view
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true
  docker.yaml: ""
