apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik
spec:
  commonName: "*.kennyandries.com"
  dnsNames:
    - "kennyandries.com"
    - "*.kennyandries.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: traefik-cert
