ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
  hosts:
    - host: actualbudget.kennyandries.com
      paths:
        - path: /
          pathType: ImplementationSpecific

persistence:
  enabled: true
  existingClaim: actualbudget-volume
