ingress:
  enabled: true
  hosts: ["pihole.kennyandries.com"]
  path: "/"
  pathType: ImplementationSpecific
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
    traefik.ingress.kubernetes.io/router.middlewares: traefik-oidc@kubernetescrd

persistentVolumeClaim:
  enabled: true

serviceDns:
  loadBalancerIP: 192.168.1.3
  type: LoadBalancer

admin:
  enabled: false

DNS1: 192.168.1.1
DNS2: 192.168.1.1

dnsmasq:
  customDnsEntries:
    - address=/kube.kennyandries.com/192.168.1.3
