apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
  namespace: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: pocket-id
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pocket-id
    spec:
      enableServiceLinks: true
      containers:
        - name: pocket-id
          image: "ghcr.io/pocket-id/pocket-id:v1.14.2"
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TRUST_PROXY
              value: "true"
            - name: APP_URL
              value: "https://auth.kennyandries.com"
          ports:
            - name: http
              containerPort: 1411
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: pocket-id
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: pocket-id
          persistentVolumeClaim:
            claimName: pocket-id
