---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBfNcQzs8B8jHXqFF8FPyo3HQuEJLTpfHK/MF2HX7Z07Y5ZaRiji+MDqeOSvWw7KeTWdfCAaSqxykgTNbAkc+6q8yqwXMCBr/UzoIEj7tGcdvZezU+GwtN6De4g2gVRrQ5u9tpUan9PjBvpsrO8y9EiRsaPR3zTPl/4HU/GBeOrbnOHz05ZYFe8b0Qr8bd1OABcMlBDcqq3TpatMVX/sAKNwS4kPQI2wsrOajcrimcE3t9338VDeyUMD8LubInvKmbxu9m7ravBDMRGMDGRkdCk3EZjCBkjaq58knA2mfyPhtPxNmf5stVGt/AvOpvUmZmc8sqDGW79GdKHZLQzSJ6th8vXfgi6Scf7oYLLozF4FCTw5a2gE0aDvgDJ/uNckOLOf8S1JydB4IvvRLypISk7JWJXwR/xUR3OyZNzCHWB1sQJkkmm1eyY43CfQZiPwYqL+0jWlJCop5rBAk2gnOoVqL9Zhk2BXChkavoS6Bz8wYmBLJpmcsxM6VplvQYbeK3pbNr29uTps1qiaClGtrCSN+LuSDmWQarXpZaU3ykp5nIk4wggbbWnJponWtDFKOY2u5DMn6Qaq8WVfNWHnJZosAI7wyXpEPH2/D4jFiXMLeYJeCpoxjNA9Q6kjr2KQ1NQ74nGRUT3xLHLLPb/XW6Q/Ke395aH84OatK2HZfR56KAL4ISYYIEyW4WuC4rY1oUVLejUh8AXRqjb1FjBRXOB0HlPcn5et/sXTpGsOb/ZbQ==
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque
