repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: cert-manager
    url: quay.io/jetstack/charts
    oci: true
  - name: cert-manager-webhook-hetzner
    url: https://vadimkim.github.io/cert-manager-webhook-hetzner
  - name: traefik
    url: https://traefik.github.io/charts
  - name: community-charts
    url: https://community-charts.github.io/helm-charts
  - name: servarr
    url: https://charts.kubito.dev

releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: v1.10.1
    values:
      - ./values/longhorn-values.yaml
  # Secrets management
  - name: sealed-secrets
    namespace: kube-system
    chart: sealed-secrets/sealed-secrets
    version: v2.17.9
  # Certificate management
  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: v1.19.1
    set:
      - name: installCRDs
        value: true
  # Hetzner support for cert-manager
  - name: cert-manager-webhook-hetzner
    namespace: cert-manager
    chart: cert-manager-webhook-hetzner/cert-manager-webhook-hetzner
    version: v1.4.0
  # Ingress controller
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: v37.4.0
    values:
      - ./values/traefik-values.yaml
  # Personal finance tool
  - name: actualbudget
    namespace: actualbudget
    chart: community-charts/actualbudget
    version: v1.8.4
    values:
      - ./values/actualbudget-values.yaml
  # Media management
  - name: servarr
    namespace: servarr
    chart: servarr/servarr
    version: v1.2.2
    values:
      - ./values/servarr-values.yaml
